### ISSUE TITLE
Cannot import existing subnet with ID displayed on console

### ISSUE THREAD

**Issue by vinayakbhat24** [OpenTelekomCloud/terraform-otc#17]
Hi,
I am not able to import a subnet with a ID which is displayed on otc console or CLI.  What I found is, when you create a subnet through terraform, terraform output displays entirely different ID from what we see it from console or CLI. And I can import with a ID that is displayed in terraform output.

Thanks,

**Comment by Crapworks** [comment]
@vinayakbhat24 

I've just checked and for some reasons the ID that is shown next to the subnet is **NOT** the subnet ID but the network ID. It looks like the subnet ID is not visible via the GUI and you have to use the openstack/neutron CLI or the OTC cli to get the subnet ID.

Cheers,
Christian

**Comment by Crapworks** [comment]
@vinayakbhat24 

Were you able to get the required IDs via API? Or do you need any help with this topic?

Cheers,
Christian
